---
:users:
  kandellak:
    :login: kandellak
    :password: passwordA
    :token: 5555555
    :applications:
      - test_app
      - cms
      - mail
      - microservices
      - libs
  noirknight:
    :login: kandellaster
    :password: passwordB
    :token: 7777777